### ISSUE TITLE
Preferred usage broken

### ISSUE THREAD

**Issue by nknapp** [nknapp/gql2ts-for-server#30]
I tried writing an [example for unions](https://github.com/nknapp/graphql-typewriter/blob/docs/examples/unions/usage.ts), but I failed due to the following facts:

* I would like to use `import {schema} from './unions.graphqls'` as import-statement, because
it makes it look like the graphqls-file itself is imported
* There is now more than only interfaces in the resulting typescript-file. That's why, `tsc` will keep the `import`-statement as `require('...')`-statement for NodeJS.
* `require('./unions.graphqls')` does not require the file `./unions.graphqls.js`, but tries to load `./unions.graphqls` as JavaScript, which obviously is not possible.

As a workaround,  `import {schema} from './unions.graphqls.js'` can be used, but that seems kind of weird in a TypeScript-project.

I wonder if it is possible to specify the `defaultResolvers` as interfaces so that no actual code is generated by TypeScript.

**Comment by msiegenthaler** [comment]
Oh, that's bad. I didn't see this problem because I'm actually using `schema.graphql` and `schema.ts` in my project. The same naming is also used inside the `test/usability-spec.ts`.

I don't think it'll be possible to just generate an interface, because it generates code that actually need to be executed.
Also I suspect the same thing would happen with enums, since they also generate a `const`.

I'd probably drop the `.graphql` in the generated files, but I see your point regarding importing the schema.

**Comment by nknapp** [comment]
I fear that there may be name-clashes with ordinary typescript files, if the `.graphqls`-part is not in the filename. How about `unions.graphqls.types.ts` or `unions.graphqls.interfaces.ts`?

**Comment by msiegenthaler** [comment]
I like the `unions.graphqls.types.ts`
